version: "3.9"

services:
  postgres:
    image: pgvector/pgvector:pg15

  minio:
    image: minio/minio
    container_name: jira_minio
    command: server /data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: adminadmin
    ports:
      - "9000:9000"

  nats:
    image: nats:2
    container_name: jira_nats
    ports:
      - "4222:4222"
